name: flake8 clearance

on: [push]

jobs: flake8 clearance
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements_tests.txt
        pip install flake8
    - name: Organizing the code with flake8
      run: |
        flake8 . --exclude *coco* --exclude *utils
